const SHORTMOVIE_DURATION = 40;
const SMALL_SCREEN_VISIBLE_MOVIES_NUMBER = 5;
const MIDDLE_SCREEN_VISIBLE_MOVIES_NUMBER = 8;
const LARGE_SCREEN_VISIBLE_MOVIES_NUMBER = 12;
const SMALL_SCREEN_ADDITIONAL_MOVIES_NUMBER = 2;
const MIDDLE_SCREEN_ADDITIONAL_MOVIES_NUMBER = 2;
const LARGE_SCREEN_ADDITIONAL_MOVIES_NUMBER = 3;


export {
  SHORTMOVIE_DURATION,
  SMALL_SCREEN_VISIBLE_MOVIES_NUMBER,
  MIDDLE_SCREEN_VISIBLE_MOVIES_NUMBER,
  LARGE_SCREEN_VISIBLE_MOVIES_NUMBER,
  SMALL_SCREEN_ADDITIONAL_MOVIES_NUMBER,
  MIDDLE_SCREEN_ADDITIONAL_MOVIES_NUMBER,
  LARGE_SCREEN_ADDITIONAL_MOVIES_NUMBER,
};